import React,{useEffect,useState} from 'react';
import {ArrowLeft,Calendar as CalendarIcon,Moon,Loader2,RefreshCw} from 'lucide-react';
import {fetchHijriDate,fetchHijriMonth,MONTHS, HijriDate} from '../../services/hijriCalendarApi';
import {toBengaliNumerals} from '../../utils/prayerCalculation';

export const CalendarScreen:React.FC<{onBack:()=>void}>=({onBack})=>{
 const [today,setToday]=useState<HijriDate|null>(null);const [month,setMonth]=useState<any[]>([]);const [customDate,setCustomDate]=useState(new Date().toISOString().slice(0,10));const [converted,setConverted]=useState<HijriDate|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const d=await fetchHijriDate();setToday(d);setMonth(await fetchHijriMonth(d.hijriYear,d.hijriMonth))}catch{setError('হিজরি ক্যালেন্ডার অনলাইন উৎস থেকে লোড করা যাচ্ছে না।')}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!customDate)return;const [y,m,d]=customDate.split('-').map(Number);fetchHijriDate(new Date(y,m-1,d)).then(setConverted).catch(()=>setConverted(null))},[customDate]);
 if(loading)return <div className="max-w-4xl mx-auto py-20 text-center"><Loader2 className="w-7 h-7 animate-spin mx-auto text-[#176B4D]"/><p className="mt-3 text-sm">হিজরি ক্যালেন্ডার লোড হচ্ছে…</p></div>;
 if(error)return <div className="max-w-4xl mx-auto p-6 text-center space-y-3"><p>{error}</p><button onClick={()=>void load()} className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-[#176B4D] text-white text-xs font-bold"><RefreshCw className="w-4 h-4"/>আবার চেষ্টা করুন</button></div>;
 const h=today!;
 return <div className="max-w-4xl mx-auto px-4 py-6 space-y-6 pb-24">
  <div className="flex items-center gap-3"><button onClick={onBack} className="p-2.5 rounded-2xl border text-[#176B4D]"><ArrowLeft className="w-5 h-5"/></button><div><h1 className="text-xl sm:text-2xl font-black">হিজরি ক্যালেন্ডার</h1><p className="text-xs text-[#717A74]">অনলাইন AlAdhan ক্যালেন্ডার</p></div></div>
  <div className="rounded-3xl p-6 bg-gradient-to-br from-[#176B4D] to-[#0E4933] text-white space-y-3"><span className="text-xs font-bold flex items-center gap-2"><Moon className="w-4 h-4"/>আজকের হিজরি তারিখ</span><div className="text-3xl font-black">{toBengaliNumerals(h.hijriDay)} {h.monthNameBn} {toBengaliNumerals(h.hijriYear)} হিজরি</div><div dir="rtl" className="text-lg">{h.hijriDay} {h.monthNameAr} {h.hijriYear} هـ</div></div>
  <div className="p-5 rounded-3xl bg-white dark:bg-[#1A221C] border space-y-3"><h2 className="font-black">তারিখ রূপান্তর</h2><div className="grid sm:grid-cols-2 gap-4"><input type="date" value={customDate} onChange={e=>setCustomDate(e.target.value)} className="px-3 py-2 rounded-xl border bg-transparent"/><div className="p-3 rounded-2xl bg-[#E8EFEA] dark:bg-[#252F28] text-sm">{converted?\`হিজরি: ${toBengaliNumerals(converted.hijriDay)} ${converted.monthNameBn} ${toBengaliNumerals(converted.hijriYear)}\`:'তারিখ পাওয়া যায়নি'}</div></div></div>
  <div className="space-y-3"><h2 className="font-black flex items-center gap-2"><CalendarIcon className="w-4 h-4 text-[#176B4D]"/>চলতি হিজরি মাস</h2><div className="grid sm:grid-cols-2 gap-2">{month.map((d:any)=><div key={d.date.gregorian} className="p-3 rounded-2xl border bg-white dark:bg-[#1A221C]"><div className="flex justify-between text-xs font-bold"><span>{d.gregorian.date}</span><span>{toBengaliNumerals(Number(d.hijri.day))} {MONTHS[Number(d.hijri.month.number)-1]?.[0]??d.hijri.month.en}</span></div></div>)}</div></div>
  <div className="text-[11px] text-[#717A74]">সূত্র: <a className="underline" href="https://aladhan.com/islamic-calendar-api" target="_blank" rel="noreferrer">AlAdhan Islamic Calendar API</a>। চাঁদ দেখা/স্থানীয় কর্তৃপক্ষের ঘোষণার কারণে তারিখে পার্থক্য হতে পারে।</div>
 </div>;
};